### ISSUE TITLE
源码运行错误

### ISSUE THREAD

**Issue by scvoet** [plutobell/teelebot#4]
- Windows 版本：Windows 10 专业工作站版（2004）x64
- Python 版本：Python 3.9.0
- requests 已安装，.config.cfg 已配置

``` powershell
PS C:\Users\Scvoet\Desktop\dev\Python\teelebot> python -m teelebot
Traceback (most recent call last):
  File "D:\Scoop\apps\python\current\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\Scoop\apps\python\current\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "D:\Scoop\apps\python\current\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Scvoet\Desktop\dev\Python\teelebot\teelebot\__init__.py", line 13, in <module>
    bot = Bot()
  File "C:\Users\Scvoet\Desktop\dev\Python\teelebot\teelebot\teelebot.py", line 39, in __init__
    self.config = config()
  File "C:\Users\Scvoet\Desktop\dev\Python\teelebot\teelebot\handler.py", line 51, in config
    options = conf.options("config")
  File "D:\Scoop\apps\python\current\lib\configparser.py", line 675, in options
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'config'
Exception ignored in: <function Bot.__del__ at 0x000002B338B79040>
Traceback (most recent call last):
  File "C:\Users\Scvoet\Desktop\dev\Python\teelebot\teelebot\teelebot.py", line 70, in __del__
    self.__thread_pool.shutdown(wait=True)
AttributeError: 'Bot' object has no attribute '_Bot__thread_pool'
```

**Comment by plutobell** [comment]
>     * Python 版本：Python 3.9.0
> 
>     * requests 已安装，.config.cfg 已配置
> 
> 
> ```powershell
> PS C:\Users\Scvoet\Desktop\dev\Python\teelebot> python -m teelebot
> Traceback (most recent call last):
>   File "D:\Scoop\apps\python\current\lib\runpy.py", line 188, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "D:\Scoop\apps\python\current\lib\runpy.py", line 147, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "D:\Scoop\apps\python\current\lib\runpy.py", line 111, in _get_module_details
>     __import__(pkg_name)
>   File "C:\Users\Scvoet\Desktop\dev\Python\teelebot\teelebot\__init__.py", line 13, in <module>
>     bot = Bot()
>   File "C:\Users\Scvoet\Desktop\dev\Python\teelebot\teelebot\teelebot.py", line 39, in __init__
>     self.config = config()
>   File "C:\Users\Scvoet\Desktop\dev\Python\teelebot\teelebot\handler.py", line 51, in config
>     options = conf.options("config")
>   File "D:\Scoop\apps\python\current\lib\configparser.py", line 675, in options
>     raise NoSectionError(section) from None
> configparser.NoSectionError: No section: 'config'
> Exception ignored in: <function Bot.__del__ at 0x000002B338B79040>
> Traceback (most recent call last):
>   File "C:\Users\Scvoet\Desktop\dev\Python\teelebot\teelebot\teelebot.py", line 70, in __del__
>     self.__thread_pool.shutdown(wait=True)
> AttributeError: 'Bot' object has no attribute '_Bot__thread_pool'
> ```

请脱敏后贴上配置文件内容

**Comment by scvoet** [comment]
@plutobell 如下
``` ini
[config]
key=14***5655:AAG****ti9T_c7***kvnxxHc*****X3lnPA
pool_size=40 //the thread pool size, default 40, range(1, 101)
webhook=False
cert_pub=your public certificate dir //Optional while webhook is False
server_ip=your server ip address //Optional while webhook is False
server_port=your server port //Optional while webhook is False
local_address=webhook local address //Optional while webhook is False
local_port=webhook local port //Optional while webhook is False
root=1319085567
debug=False
timeout=60
plugin_dir=your plugin dir   //[Optional]
```

**Comment by plutobell** [comment]
> @plutobell 如下
> 
> ```ini
> [config]
> key=14***5655:AAG****ti9T_c7***kvnxxHc*****X3lnPA
> pool_size=40 //the thread pool size, default 40, range(1, 101)
> webhook=False
> cert_pub=your public certificate dir //Optional while webhook is False
> server_ip=your server ip address //Optional while webhook is False
> server_port=your server port //Optional while webhook is False
> local_address=webhook local address //Optional while webhook is False
> local_port=webhook local port //Optional while webhook is False
> root=1319085567
> debug=False
> timeout=60
> plugin_dir=your plugin dir   //[Optional]
> ```

        在Windows环境下，默认配置文件路径为用户目录下的 .teelebot 文件夹，请检查该路径下是否具有正确的配置文件。
        若需要手动指定配置文件，请使用命令行参数 -c/--config

**Comment by scvoet** [comment]
文件夹命名缺少了一个 `e`，感谢

**Comment by plutobell** [comment]
> 文件夹命名缺少了一个 `e`，感谢

😃
